fix: prevent incrementation of nil counts
Fixes:

```
/Users/mhenrixon/.gem/ruby/3.4.4/gems/fuubar-2.5.1/lib/fuubar.rb:79:in 'Fuubar#example_failed': undefined method '+' for nil (NoMethodError)

    self.failed_count += 1
                      ^
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:210:in 'block in RSpec::Core::Reporter#notify'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:209:in 'Array#each'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:209:in 'RSpec::Core::Reporter#notify'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:145:in 'RSpec::Core::Reporter#example_failed'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:484:in 'RSpec::Core::Example#finish'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:442:in 'RSpec::Core::Example#fail_with_exception'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:621:in 'block in RSpec::Core::ExampleGroup.run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:663:in 'Array#each'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:663:in 'RSpec::Core::ExampleGroup.for_filtered_examples'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:621:in 'RSpec::Core::ExampleGroup.run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'block (3 levels) in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'Array#map'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'block (2 levels) in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/configuration.rb:2097:in 'RSpec::Core::Configuration#with_suite_hooks'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:116:in 'block in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:74:in 'RSpec::Core::Reporter#report'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:115:in 'RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:89:in 'RSpec::Core::Runner#run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:71:in 'RSpec::Core::Runner.run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:45:in 'RSpec::Core::Runner.invoke'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/exe/rspec:4:in '<top (required)>'
	from /Users/mhenrixon/Code/zazu/app/bin/rspec:27:in 'Kernel#load'
	from /Users/mhenrixon/Code/zazu/app/bin/rspec:27:in '<main>'
/Users/mhenrixon/.gem/ruby/3.4.4/gems/fuubar-2.5.1/lib/fuubar.rb:67:in 'Fuubar#example_passed': undefined method '+' for nil (NoMethodError)

    self.passed_count += 1
                      ^
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:210:in 'block in RSpec::Core::Reporter#notify'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:209:in 'Array#each'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:209:in 'RSpec::Core::Reporter#notify'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:139:in 'RSpec::Core::Reporter#example_passed'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:493:in 'RSpec::Core::Example#finish'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:293:in 'RSpec::Core::Example#run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:653:in 'block in RSpec::Core::ExampleGroup.run_examples'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in 'Array#map'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in 'RSpec::Core::ExampleGroup.run_examples'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:614:in 'RSpec::Core::ExampleGroup.run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'block (3 levels) in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'Array#map'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in 'block (2 levels) in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/configuration.rb:2097:in 'RSpec::Core::Configuration#with_suite_hooks'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:116:in 'block in RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:74:in 'RSpec::Core::Reporter#report'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:115:in 'RSpec::Core::Runner#run_specs'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:89:in 'RSpec::Core::Runner#run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:71:in 'RSpec::Core::Runner.run'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:45:in 'RSpec::Core::Runner.invoke'
	from /Users/mhenrixon/.gem/ruby/3.4.4/gems/rspec-core-3.13.5/exe/rspec:4:in '<top (required)>'
	from /Users/mhenrixon/Code/zazu/app/bin/rspec:27:in 'Kernel#load'
	from /Users/mhenrixon/Code/zazu/app/bin/rspec:27:in '<main>'
```

Signed-off-by: mhenrixon <mikael@mhenrixon.com>

Signed-off-by: mhenrixon <mikael@mhenrixon.com>